### ISSUE TITLE
Split a Collection into 2 lists and subscribe both?

### ISSUE THREAD

**Issue by eneim** [akarnokd/ixjava#12]
My use case is as follow:

- A collection of Box as source: boxes.

- There are red boxes and blue boxes in source.

- Once I "press the button" (start the stream), it will split the boxes into 2 lists by box's color, and I could subscribe to the value contain both of them.

My imagine is as follow (seudo):

```java
Ix.from(source)
.split((predicate) -> predicate.apply(box) /* return true if box is red, false otherwise*/)
.subscribe((redBoxes, blueBoxes) -> { /* do something, maybe share them with friends */})
```

How can I archive this behaviour with your current implementation? If it is not possible now, any opinion on why and how?

P/S: I know about the "except" operator. But it ends up creating extra Collection which I want to avoid.

Thanks.

**Comment by akarnokd** [comment]
I think you need `groupBy` (and otherwise the terminology doesn't match up with IxJava) so not sure what you want to achieve with that syntax as neither IxJava nor RxJava support multi-value consumption per signal notifications.

```java
source
.groupBy(v -> isRed(v))
.flatMap(g -> g.collectToList())
.buffer()
.foreach(groups -> { 
    System.out.println(group.get(0));
    System.out.println(group.get(1));
});
```

**Comment by eneim** [comment]
Oh @akarnokd thanks, I think what I want at the terminal is to subscribe to both the values but I forget the "foreach" operator. I will try your suggestion.
