### ISSUE TITLE
[Security] Workflow gradle-wrapper-validation.yml is using vulnerable action gradle/wrapper-validation-action

### ISSUE THREAD

**Issue by Ale0x78** [akarnokd/ixjava#16]
The workflow gradle-wrapper-validation.yml is referencing action gradle/wrapper-validation-action using references v1. However this reference is missing the commit [89eda1fdc0167f59521d2bb10767f7169fb4d018](https://github.com/gradle/wrapper-validation-action/commits/89eda1fdc0167f59521d2bb10767f7169fb4d018) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by akarnokd** [comment]
Thanks. Closing via https://github.com/akarnokd/ixjava/commit/90ff3f6ea46c91a2d30d474e50c340a5201a3e5a .
