### ISSUE TITLE
Bring This Under ReativeX umbrella

### ISSUE THREAD

**Issue by sirinath** [akarnokd/ixjava#3]
Can this be moved under the ReactiveX umbrella? Also Reactor can make do with a similar API.

**Comment by akarnokd** [comment]
I thought about it some time ago but there was no apparent demand for this library (see how few stars and forks this has). On the JVM, this is competing with Java 8 streams and similar built-in features of other languages. In addition, we made so significant performance improvements in Reactor/4th gen reactive libraries that now running your synchronous flow is only 15% slower with an equivalen IxJava flow in general. Thanks for your interest and support anyway!

**Comment by sirinath** [comment]
Nobody knows about it and currently it has not got the proper exposure. This will give it the proper exposure. Also in the current scheme of things it looks like it is dependent on one developer. This also will change if you more it to ReactiveX.

**Comment by akarnokd** [comment]
Probably. Let's get back to this issue after we released RxJava 2.0 in late October.

**Comment by sirinath** [comment]
I was thinking perhaps you can simultaneously release IX with 2.0 time line? Ideally if this is part of the larger project it might also get other contributors.

Also how about similar extension for project reactor?

**Comment by akarnokd** [comment]
Now that I'm leading RxJava and co-leading Reactor, both very close to GA, I simply don't have the capacity to 'battle' this out with ReactiveX.

Besides, Reactor and Rsc are Java 8 and thus Java Streams are present as the built-in alternative. I'm interacting with Reactor on a daily basis and they haven't expressed any interest for this kind of synchronous library. But don't worry, once RxJava 2.0 gets RC 1, I plan to add a 2.x branch which will support Reactive-Streams conversions. That should cover everybody, including Rsc.

**Comment by sirinath** [comment]
OK. Once you get to  RxJava 2.0 gets RC 1 then transfer this repository to https://github.com/ReactiveX/ organisation.

**Comment by sirinath** [comment]
Any possibility of this? Just checking.

**Comment by akarnokd** [comment]
No.
