### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by Petikoch** [akarnokd/ixjava#6]
Hello @akarnokd ,

I don't grok it (immediately)... what about a small code example on "page 1" (README.md)

Thanks and best regards from Switzerland,
Peti

**Comment by akarnokd** [comment]
Updated.

**Comment by Petikoch** [comment]
Excellent. Thanks!

Just one final note: Would "**Iterable** Extensions for Java" be a better subtitle than "Interactive Extensions for Java"?

Best regards,
Peti

**Comment by akarnokd** [comment]
"Interactive" is the classic name as this comes from 2011 and Ix.NET. Luckily, the "I" in Ix can mean both. Will consider it before final.

**Comment by Petikoch** [comment]
I'd vote for "Iterable", since this every Java programmer understands. 
"Interactive" is such a broad term and has no special meaning on the JVM. 

But that's just my humble opinion. 

Best regards & thanks for your work.
Peti
